// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi0Tv5E3cDlupJMYLmwIuiK3Q0fjtlMso',
    appId: '1:644055839812:web:f3a595c73ae5b6ed193811',
    messagingSenderId: '644055839812',
    projectId: 'test-9antratn',
    authDomain: 'test-9antratn.firebaseapp.com',
    storageBucket: 'test-9antratn.firebasestorage.app',
    measurementId: 'G-ZQGKRM0DNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy6Lf6N1aueeNrbTtGBwXhxeHrxXa5DCc',
    appId: '1:644055839812:android:16c6c662bdfedadb193811',
    messagingSenderId: '644055839812',
    projectId: 'test-9antratn',
    storageBucket: 'test-9antratn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDonM443A1Z8cK1KQvYqwMfRfWcMlw8Z3k',
    appId: '1:644055839812:ios:aa4491217bdb70d5193811',
    messagingSenderId: '644055839812',
    projectId: 'test-9antratn',
    storageBucket: 'test-9antratn.firebasestorage.app',
    iosBundleId: 'com.example.beecoderstest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDonM443A1Z8cK1KQvYqwMfRfWcMlw8Z3k',
    appId: '1:644055839812:ios:aa4491217bdb70d5193811',
    messagingSenderId: '644055839812',
    projectId: 'test-9antratn',
    storageBucket: 'test-9antratn.firebasestorage.app',
    iosBundleId: 'com.example.beecoderstest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi0Tv5E3cDlupJMYLmwIuiK3Q0fjtlMso',
    appId: '1:644055839812:web:0b0a665deecee359193811',
    messagingSenderId: '644055839812',
    projectId: 'test-9antratn',
    authDomain: 'test-9antratn.firebaseapp.com',
    storageBucket: 'test-9antratn.firebasestorage.app',
    measurementId: 'G-P1PN55B32S',
  );
}
